# Generated by Django 3.2.7 on 2021-10-28 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_image1', models.ImageField(default='default_product.png', upload_to='product/%Y/%m/%d')),
                ('product_image2', models.ImageField(default='default_product.png', upload_to='product/%Y/%m/%d')),
                ('product_image3', models.ImageField(default='default_product.png', upload_to='product/%Y/%m/%d')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
