# Generated by Django 3.2.7 on 2021-10-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_sale',
            field=models.BooleanField(default=True),
        ),
    ]
